/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllowedCategoriesSection: typeof import('./src/components/AllowedCategoriesSection.vue')['default']
    BudgetFormDialog: typeof import('./src/components/BudgetFormDialog.vue')['default']
    CategoryFormDialog: typeof import('./src/components/CategoryFormDialog.vue')['default']
    CategoryPicker: typeof import('./src/components/CategoryPicker.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DependentFormDialog: typeof import('./src/components/DependentFormDialog.vue')['default']
    DependentPicker: typeof import('./src/components/DependentPicker.vue')['default']
    ExpenseFormDialog: typeof import('./src/components/ExpenseFormDialog.vue')['default']
    OverspendBanner: typeof import('./src/components/OverspendBanner.vue')['default']
    PocketMoneyFormDialog: typeof import('./src/components/PocketMoneyFormDialog.vue')['default']
    ResourceState: typeof import('./src/components/ResourceState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
