DEFAULT_CATEGORIES = [
	("Food", "🍽️"),
	("Food Delivery", "🍕"),
	("Transport", "🚌"),
	("Shopping", "🛒"),
	("Entertainment", "🎬"),
	("Bills", "📄"),
	("Healthcare", "🏥"),
	("Fitness", "💪"),
	("Education", "📚"),
	("Travel", "✈️"),
	("Salary", "💰"),
	("Miscellaneous", "📦"),
	("Uncategorized", "❓"),
]

CATEGORY_ALIASES = {
	"food delivery": "Food Delivery",
	"zomato": "Food Delivery",
	"swiggy": "Food Delivery",
	"ubereats": "Food Delivery",
	"uber eats": "Food Delivery",
	"eat": "Food Delivery",
	"dinner": "Food",
	"lunch": "Food",
	"breakfast": "Food",
	"groceries": "Food",
	"grocery": "Food",
	"restaurant": "Food",
	"cafe": "Food",
	"coffee": "Food",
	"snacks": "Food",
	"gym": "Fitness",
	"workout": "Fitness",
	"exercise": "Fitness",
	"sports": "Fitness",
	"petrol": "Transport",
	"diesel": "Transport",
	"fuel": "Transport",
	"gas": "Transport",
	"uber": "Transport",
	"ola": "Transport",
	"cab": "Transport",
	"taxi": "Transport",
	"bus": "Transport",
	"train": "Transport",
	"metro": "Transport",
	"movie": "Entertainment",
	"movies": "Entertainment",
	"cinema": "Entertainment",
	"concert": "Entertainment",
	"netflix": "Entertainment",
	"prime": "Entertainment",
	"spotify": "Entertainment",
	"subscription": "Entertainment",
	"game": "Entertainment",
	"games": "Entertainment",
	"electricity": "Bills",
	"water": "Bills",
	"internet": "Bills",
	"phone": "Bills",
	"rent": "Bills",
	"bill": "Bills",
	"medicine": "Healthcare",
	"medicines": "Healthcare",
	"medical": "Healthcare",
	"doctor": "Healthcare",
	"hospital": "Healthcare",
	"clinic": "Healthcare",
	"chemist": "Healthcare",
	"pharmacy": "Healthcare",
	"books": "Education",
	"book": "Education",
	"course": "Education",
	"fees": "Education",
	"tuition": "Education",
	"class": "Education",
	"flight": "Travel",
	"flights": "Travel",
	"hotel": "Travel",
	"hotels": "Travel",
	"vacation": "Travel",
	"trip": "Travel",
	"holiday": "Travel",
	"clothes": "Shopping",
	"clothing": "Shopping",
	"apparel": "Shopping",
	"electronics": "Shopping",
	"amazon": "Shopping",
	"flipkart": "Shopping",
	"myntra": "Shopping",
	"online": "Shopping",
	"gadget": "Shopping",
	"gadgets": "Shopping",
}
